# Generated by Django 4.1 on 2023-05-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_name', models.CharField(max_length=100)),
                ('Event_description', models.CharField(max_length=100)),
                ('Event_date', models.DateField()),
                ('Event_time', models.TimeField()),
                ('Event_location', models.CharField(max_length=100)),
                ('Event_Likes', models.IntegerField(default=0)),
                ('Event_Image', models.ImageField(default='images/None/No-img.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.events')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.users')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='Event_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.users'),
        ),
        migrations.CreateModel(
            name='EnrolledEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.events')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('Comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Comment_text', models.CharField(max_length=100)),
                ('Comment_date', models.DateField()),
                ('Comment_time', models.TimeField()),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.events')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.users')),
            ],
        ),
    ]
