# Generated by Django 4.1 on 2023-05-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.events')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF_API.users')),
            ],
        ),
    ]
